---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 776114469315284992-CrylMtkSqCAOCY76C9oBQ5aGdYPOVhp
:access_token_secret: HUkNR8GPIYM5b4IECk0m4iFDRVQ0tLgbIjvmZ7L956DrD
